package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSeries;
import org.linlinjava.litemall.db.domain.LitemallSeriesExample;

public interface LitemallSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    long countByExample(LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int insert(LitemallSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    LitemallSeries selectOneByExample(LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    LitemallSeries selectOneByExampleSelective(@Param("example") LitemallSeriesExample example, @Param("selective") LitemallSeries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    List<LitemallSeries> selectByExampleSelective(@Param("example") LitemallSeriesExample example, @Param("selective") LitemallSeries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    List<LitemallSeries> selectByExample(LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    LitemallSeries selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSeries.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    LitemallSeries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    LitemallSeries selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSeries record, @Param("example") LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSeries record, @Param("example") LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_series
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}