package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallNav;
import org.linlinjava.litemall.db.domain.LitemallNavExample;

public interface LitemallNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    long countByExample(LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int insert(LitemallNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int insertSelective(LitemallNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    LitemallNav selectOneByExample(LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    LitemallNav selectOneByExampleSelective(@Param("example") LitemallNavExample example, @Param("selective") LitemallNav.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    List<LitemallNav> selectByExampleSelective(@Param("example") LitemallNavExample example, @Param("selective") LitemallNav.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    List<LitemallNav> selectByExample(LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    LitemallNav selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallNav.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    LitemallNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    LitemallNav selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallNav record, @Param("example") LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallNav record, @Param("example") LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_nav
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}