package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCustomized;
import org.linlinjava.litemall.db.domain.LitemallCustomizedExample;

public interface LitemallCustomizedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    long countByExample(LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int insert(LitemallCustomized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCustomized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    LitemallCustomized selectOneByExample(LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    LitemallCustomized selectOneByExampleSelective(@Param("example") LitemallCustomizedExample example, @Param("selective") LitemallCustomized.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    List<LitemallCustomized> selectByExampleSelective(@Param("example") LitemallCustomizedExample example, @Param("selective") LitemallCustomized.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    List<LitemallCustomized> selectByExample(LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    LitemallCustomized selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCustomized.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    LitemallCustomized selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    LitemallCustomized selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCustomized record, @Param("example") LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCustomized record, @Param("example") LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCustomized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCustomized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallCustomizedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_customized
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}