package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallProduct;
import org.linlinjava.litemall.db.domain.LitemallProductExample;

public interface LitemallProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    long countByExample(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int insert(LitemallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int insertSelective(LitemallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectOneByExample(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectOneByExampleSelective(@Param("example") LitemallProductExample example, @Param("selective") LitemallProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectOneByExampleWithBLOBs(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    List<LitemallProduct> selectByExampleSelective(@Param("example") LitemallProductExample example, @Param("selective") LitemallProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    List<LitemallProduct> selectByExampleWithBLOBs(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    List<LitemallProduct> selectByExample(LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    LitemallProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallProduct record, @Param("example") LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallProduct record, @Param("example") LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallProduct record, @Param("example") LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}