spring:
  profiles:
    active: db, core, kudo
  messages:
    encoding: UTF-8

server:
  port: 8084

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR
